
import Head from "next/head";
import AdAccepted from "../Components/educational_dashboard/admission/AdAccepted";
import AdmissionAcpted from "../Components/educational_dashboard/admission/AdmissionAcpted";
import AdmissionCanceled from "../Components/educational_dashboard/admission/AdmissionCanceled";
import AdmitedSuccess from "../Components/educational_dashboard/admission/AdmitedSuccess";
import CancelPop from "../Components/educational_dashboard/admission/CancelPop";
import ClassSection from "../Components/educational_dashboard/admission/ClassSection";
import NoAdmission from "../Components/educational_dashboard/admission/NoAdmission";
import RequireDoc from "../Components/educational_dashboard/admission/RequireDoc";
import SetAdReqDoc from "../Components/educational_dashboard/admission/SetAdReqDoc";
import StdOfflineAccept from "../Components/educational_dashboard/admission/StdOfflineAccept";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="w-screen overflow-x-hidden">
        {/* <Addnotice></Addnotice>
      <Notice></Notice>
      <Noticeinfo></Noticeinfo>
     <Nofile></Nofile> */}
        {/* <OfflineSearch></OfflineSearch>
        <OnlineSearch></OnlineSearch>
        <OfflineTime></OfflineTime>
        <OnlineTime></OnlineTime>
        <Accepted></Accepted>
        <Canceled></Canceled>
        <AppoinmentEnd></AppoinmentEnd>
        <CancelRequest></CancelRequest>
        <Datetime></Datetime>
        <SentCancel></SentCancel>
        <Addpatient></Addpatient>
        <Nopatient></Nopatient>
        <Registration></Registration>
        <AddPatientList></AddPatientList>
        <Noonlinepatient></Noonlinepatient>
        <RequestAccepted></RequestAccepted>
        <RequestCanceled></RequestCanceled>
        <RequestSent></RequestSent>
        <WaitForAccept></WaitForAccept> */}

        {/* admission multiple */}
        <AdAccepted></AdAccepted>
        <AdmissionAcpted></AdmissionAcpted>
        <AdmissionCanceled></AdmissionCanceled>
        <AdmitedSuccess></AdmitedSuccess>
        <CancelPop></CancelPop>
        <ClassSection></ClassSection>
        <NoAdmission></NoAdmission>
        <SetAdReqDoc></SetAdReqDoc>
        <RequireDoc></RequireDoc>
        <StdOfflineAccept></StdOfflineAccept>



      </main>
    </div>
  );
}